name: deploy

on:
    push:
        branches: [ master, develop ]

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
                with:
                    ref: master

            -   name: Set up JDK 21
                uses: actions/setup-java@v3
                with:
                    java-version: '21'
                    distribution: 'corretto'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Build master branch
                run: |
                    mkdir -p build/out
                    ./gradlew jsBrowserDistribution
                    mv build/dist/js/productionExecutable/* ./build/out

            -   name: Check out develop branch
                uses: actions/checkout@v4
                with:
                    ref: develop
                    path: beta
                    clean: false

            -   name: Build develop branch
                run: |
                    cd beta
                    ./gradlew jsBrowserDistribution
                    mkdir ../build/out/beta
                    mv build/dist/js/productionExecutable/* ../build/out/beta

            -   name: Upload artifact
                uses: actions/upload-pages-artifact@v3
                with:
                    path: './build/out'

    deploy:
        needs: build

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
